name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: release-artifacts
          path: release    
      - name: Signs with Dilithium
        uses: theQRL/actions-dilithium-sign@v1
        with:
          patterns: |
            release/
          hexseed: ${{ secrets.DILITHIUM_HEXSEED }}
      - name: Upload signature file as artifact
        uses: actions/upload-artifact@master
        with:
          name: result
          path: signatures.txt